version: '3'
services:
  stan:
    image: nats-streaming
    volumes:
      - ./config:/cfg
    command: -sc /cfg/server.conf
    ports:
      - "4222:4222"
  splitter:
    build: .
    restart: always
    depends_on:
      - stan
    volumes:
      - ./config:/cfg
    environment:
      SRC_NATS_URL: "nats://10.99.100.156:4222"
      SRC_STAN_CLUSTER: "test_cluster_name"
      SRC_SUB_SUBJECT: "producer"
      STAN_CLIENT: "test_compose"
      SEPARATOR_NAME: "sep"
      DST_FILE_LOC: "/cfg/dsts.json"